apiVersion: v1
kind: Service
metadata:
  name: nowigence-retail-backend
spec:
  selector:
    app: nowigence-retail-backend
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nowigence-retail-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nowigence-retail-backend
  template:
    metadata:
      labels:
        app: nowigence-retail-backend
    spec:
      containers:
        - name: nowigence-retail-backend
          image: aadilraza339/nowigence-retail-backend:518f85330bcb819040322eaa16c000920af4f50d
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/retail-db
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"