apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nowigence-retail-backend
  namespace: default
spec:
  # Specifies the target deployment for autoscaling
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nowigence-retail-backend
  # Minimum number of replicas to scale down to
  minReplicas: 1
  # Maximum number of replicas to scale up to
  maxReplicas: 10
  # The target CPU utilization percentage for autoscaling
  # The HPA will aim to keep the average CPU utilization of pods at 70%
  targetCPUUtilizationPercentage: 70
